### ISSUE TITLE
Speed up ImageMagick installation process

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/media-command#27]
Installing ImageMagick adds about six minutes to every build:

![image](https://user-images.githubusercontent.com/36432/27795459-16b8c27e-5fbb-11e7-8305-9dc5ad0ec581.png)

Can we speed this up somehow?

**Comment by gitlost** [comment]
This should only happen if it doesn't use the cached version (see https://github.com/wp-cli/media-command/issues/7#issuecomment-292740554) otherwise it should only add 20 to 30 seconds
![screenshot from 2017-07-03 22-20-02](https://user-images.githubusercontent.com/481982/27808222-57966a20-603e-11e7-9d89-ccb6d5ac7055.png)
(see https://travis-ci.org/wp-cli/media-command/builds/247529077?utm_source=github_status&utm_medium=notification).

**Comment by danielbachhuber** [comment]
> This should only happen if it doesn't use the cached version

Is it possible to create a more permanent cache? I seem to have run into it more often than I expected.

**Comment by gitlost** [comment]
That's weird, I just tried it now there and it was ok. Looking at https://travis-ci.org/wp-cli/media-command/pull_requests the only ones not to use the cache are the two recent `--skip-copy` builds.

> Is it possible to create a more permanent cache?

There doesn't seem to be any time limit thing on it based on that listing.

**Comment by danielbachhuber** [comment]
Calling this `wontfix` because it's already cached reasonably enough. Thanks for your input, @gitlost.
