### ISSUE TITLE
Media regenerating is slow

### ISSUE THREAD

**Issue by kevincolten** [wp-cli/media-command#73]
Should media regenerating be so slow? I was only able to do about 800 (out of 13000) images last night. The process is only using 1-3% CPU. Does anyone have any tips to speed this up?

**Comment by schlessera** [comment]
@kevincolten This depends on a lot of factors, like server I/O, plugins that hook into the media process, ...

Most of the time, the slowness comes from a plugin that recompresses and optimizes images. It will do this for every single generated thumbnail, so that's quite a bit of processing. Also, depending on which plugin you use, the optimization is not done on the server itself, but the image is uploaded to a service, compressed there, and then downloaded again. This does not consume much CPU, as the bottleneck is the network transfer then.

That being said, GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. Feel free to head over to the #cli channel in the Make WordPress Slack team if you want to discuss further.
