### ISSUE TITLE
ERROR: No "medium_large" thumbnail regeneration needed for...

### ISSUE THREAD

**Issue by WorldsEndless** [wp-cli/media-command#77]
When I run `wp media regenerate 10927 --image_size=medium_large` I receive this:

```
Found 1 image to regenerate.
1/1 No "medium_large" thumbnail regeneration needed for "Bay" (ID 10927).
```

However, I DO need that image regenerated. Why is it saying I don't, and how do I override?

**Comment by schlessera** [comment]
@WorldsEndless Can you share some more details about this? What is the specific reason why it needs to be regenerated if it already exists? Is the current thumbnail broken, out-of-date, badly sized, ...?

**Comment by maugelves** [comment]
Researching a little bit then I understood that there was no need to regenerate because the original picture was smaller than the size I specified in the command.

Still, the message could be a little bit more clear (or at least in the documentation).

For example:

1/1 No "medium_large" thumbnail regeneration needed for "Bay" (ID 10927), the original picture is smaller than the size specified.

**Comment by schlessera** [comment]
@WorldsEndless I assume for now that your issue is the same one than @maugelves had.

I'm closing this issue for now in favor of https://github.com/wp-cli/media-command/issues/95

**Comment by ant0nioli** [comment]
I have the same problem with wp-cli. 
On the other hand with the Alex Mills [Regenerate Thumbnails](https://wordpress.org/plugins/regenerate-thumbnails) the regeneration works, but is not what I need.
Thk
